# Generated by Django 3.2.5 on 2021-07-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contacto_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('raza', models.CharField(max_length=12)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='mascotas')),
                ('detalles', models.TextField(max_length=13, null=True)),
            ],
        ),
    ]
