# Generated by Django 3.2.5 on 2021-07-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='detalles',
            field=models.TextField(null=True),
        ),
    ]
