# Generated by Django 3.2.5 on 2021-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210713_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueno', models.CharField(max_length=150)),
                ('nombre_mascota', models.CharField(max_length=150)),
                ('raza', models.CharField(max_length=12)),
                ('edad', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='mascotas')),
                ('detalles', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
